verions:
  latest: 0.12.0-linux-amd64
  0.12.0-linux-amd64:
    source: https://github.com/prometheus/alertmanager/releases/download/v0.12.0/alertmanager-0.12.0.linux-amd64.tar.gz
    source_hash: https://github.com/prometheus/alertmanager/releases/download/v0.12.0/sha256sums.txt
  0.6.2.linux-amd64:
    source: https://github.com/prometheus/alertmanager/releases/download/v0.6.2/alertmanager-0.6.2.linux-amd64.tar.gz
    source_hash: sha256=8b796592b974a1aa51cac4e087071794989ecc957d4e90025d437b4f7cad214a