# -*- coding: utf-8 -*-
# vim: ft=yaml
default:
  user: prometheus
  group: prometheus
  home: /var/lib/prometheus
  server:
    install_dir: /opt/prometheus/
    discovery:
      file:
        target_file: /var/lib/prometheus/targets/saltnodes.json
    args:
      config_file: /etc/prometheus/prometheus.yml
      alerting_rules_file: /etc/prometheus/prometheus_alerting_rules.yml
      storage:
        local_path: /var/lib/prometheus/metrics
        targets: /var/lib/prometheus/targets

    default_version: "2.0.0.linux-amd64"
    versions:
      1.6.3.linux-amd64:
        source: https://github.com/prometheus/prometheus/releases/download/v1.6.3/prometheus-1.6.3.linux-amd64.tar.gz
        source_hash: sha256=bb4e3bf4c9cd2b30fc922e48ab584845739ed4aa50dea717ac76a56951e31b98

      2.0.0.linux-amd64:
        source: https://github.com/prometheus/prometheus/releases/download/v2.0.0/prometheus-2.0.0.linux-amd64.tar.gz
        source_hash: sha256=e12917b25b32980daee0e9cf879d9ec197e2893924bd1574604eb0f550034d46

  alertmanager:
    instal_dir: /opt/prometheus/
    args:
      config_file: /etc/prometheus/alertmanager.yml
      storage:
        local_path: /var/lib/prometheus/alertmanager
    default_version: 0.12.0.linux-amd64
    verions:
      0.12.0-linux-amd64:
        source: https://github.com/prometheus/alertmanager/releases/download/v0.12.0/alertmanager-0.12.0.linux-amd64.tar.gz
        source_hash: https://github.com/prometheus/alertmanager/releases/download/v0.12.0/sha256sums.txt
      0.6.2.linux-amd64:
        source: https://github.com/prometheus/alertmanager/releases/download/v0.6.2/alertmanager-0.6.2.linux-amd64.tar.gz
        source_hash: sha256=8b796592b974a1aa51cac4e087071794989ecc957d4e90025d437b4f7cad214a


  exporter:
    node:
      version: 0.14.0.linux-amd64
      install_dir: /opt
      source: https://github.com/prometheus/node_exporter/releases/download/v0.14.0/node_exporter-0.14.0.linux-amd64.tar.gz
      source_hash: sha256=d5980bf5d0dc7214741b65d3771f08e6f8311c86531ae21c6ffec1d643549b2e
    haproxy:
      version: 0.7.1.linux-amd64
      install_dir: /opt
      source: https://github.com/prometheus/haproxy_exporter/releases/download/v0.7.1/haproxy_exporter-0.7.1.linux-amd64.tar.gz
      source_hash: sha1=56849253e280db3db2aa80f1013ecfe242536d32
      args:
        scrape_uri: 'unix:/run/haproxy/admin.sock'